/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Family;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
	/*
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    */
	
    @Test
    public void testFun() {
    	Library obj = new Library();
    	obj.fun();
    	assertTrue("hariom",true);
    }
    
}
