/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Family;

public class Library {
    /*
	public boolean someLibraryMethod() {
        return true;
    }
    */
    
    public String fun() {
    	return "hari";
    }
}
